### ISSUE TITLE
Tracking issue: Performance with large message sizes on Node.js

### ISSUE THREAD

**Issue by ofrobots** [grpc/grpc#10642]
We recently investigated performance with the BigTable client library on Node.js and discovered some performance issues (CPU usage, latency) with large message sizes. This is a tracking issue for the relevant fixes

* [x] Need performance test-coverage for large message sizes (1B-1KB-10KB-1MB-max_limit) 
* [ ] Performance fixes
  * [X] Upgrade to protobufjs@6 (https://github.com/grpc/grpc/pull/10204)
  * [X] Performance improvements (https://github.com/grpc/grpc/pull/10416)
  * [x] Release these performance fixes
  * [ ] Investigate the outstanding 2.5X performance difference on large message sizes vs. REST
  * [ ] Investigate performance improvements in core TLS code

**Comment by murgatroid99** [comment]
Another item on the list should probably be improvements to the core TLS code. Using TLS has a greater performance hit than it probably should.

**Comment by murgatroid99** [comment]
I have created benchmarks to test latency with response messages of various sizes. The data from those benchmarks can be found here: http://performance-dot-grpc-testing.appspot.com/explore?dashboard=5717648100818944. As you can see, according this benchmark, JSON over HTTP is significantly slower than proto over gRPC, and this difference scales with message size.

I would not claim that these benchmarks definitively indicate that gRPC is faster that REST, but I no longer believe that we can trust the old benchmark indicating a "2.5x performance difference" in the other direction.

**Comment by ofrobots** [comment]
As it stands, right now we have two different benchmarks with different results. We still need a disposition on the benchmark that shows the 2.5x performance difference – I think you can reproduce this too. Since it is reproducible, it would be good to show why it is not relevant – or to fix the issue(s), if it is relevant.
