### ISSUE TITLE
Turn warnings of the C core back on, and create issues for them

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2102]
To turn them on: https://github.com/grpc/grpc/blob/master/gRPC.podspec#L39

I created this as a tracking issue for them, because it's going to take a while to fix them all.

This has 2 parts:

 - [x] Implicit integer conversion in the C core (#2127)
 - [ ] Unreachable code in the C core (#2128)

**Comment by murgatroid99** [comment]
This has 2 parts:

 - [ ] Implicit integer conversion in the C core (#2127)
 - [ ] Unreachable code in the C core (#2128)

**Comment by murgatroid99** [comment]
#2128 is now closed, so I think this can be closed too.
