### ISSUE TITLE
pkg-config support (tracking bug)

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#2231]
We should do the following:

 - [x] Use `pkg-config` to check dependencies (protobuf, openssl) when possible in the Makefile. (#2233)
 - [x] Install `.pc` files for `gpr` and `grpc` libraries. (#2253)
 - [ ] Use `pkg-config` for the `grpc` dependency in wrapped language build scripts.
 - [ ] Modify the tests

Then we should change the homebrew script to only install the core and C++ libraries, because homebrew interacts well with `pkg-config` and this would allow us to use standard language tools `npm`, `pip`, `gem`, etc. to install the wrapped language packages.

This should allow us to more easily fix #2220, grpc/grpc-common#233, grpc/homebrew-grpc#31, and grpc/homebrew-grpc#32 (and possibly others).

**Comment by murgatroid99** [comment]
PHP is a little tricky, because of the Autoconf->Automake->make build process that is more complicated than the other languages. There is an autoconf macro for `pkg-config`, but if `pkg-config` is not present in the system, autoconf will just fail. Alternatively, we can use the same build-time `pkg-config` detection we use with the other languages, but the multiple levels of code transformation make it unclear how that will interact with the autoconf stuff.

**Comment by jayantkolhe** [comment]
moving to GA

**Comment by murgatroid99** [comment]
I think the unfinished parts of this have basically become irrelevant due to recent installation work. Any wrapped language library that would have used pkg-config like this now instead bundles the C core directly.
