### ISSUE TITLE
Tracking issue: publish the beta debian package (tag: 0.11.0)

### ISSUE THREAD

**Issue by tbetbetbe** [grpc/grpc#3283]

**Comment by tbetbetbe** [comment]
@hsaliak, @a11r, @jayantkolhe PTAL

**Comment by tbetbetbe** [comment]
FYI: this has not been uploaded yet.
- the documentation that we added is causing errors in the lintian step used to confirm that the deb package is valid.  @andrewpollock is taking a look to see if we can do something to link the docs the src they come from.

**Comment by tbetbetbe** [comment]
@hsaliak, @a11r, @jayantkolhe FYI

Ok, the debian package is published; this issue is open until it reaches jessie-backports

Stage reached:
- [x] [debian-sid](https://packages.debian.org/source/sid/grpc)
- [ ] debian-testing (ETA 11/20/2015)
- [ ] jessie-backports (ETA 11/21/2015)

**Comment by tbetbetbe** [comment]
For the record, the issue with docs was resolved by removing them from the sid branch; the current plan is to remove them from the main and release branches as well and replace with a build rule. (cf #3313)

**Comment by jtattermusch** [comment]
Hopefully, the ETA 11/20/2015 is wrong :-)

Also, it is worth noting that grpc C core debian package won't be useful until protobuf-3.0.0-beta1 gets released as a debian package and grpc protoc plugins will be released as a debian package as well.

**Comment by tbetbetbe** [comment]
This is completed
[libgrpc-dev in jessie-backports](https://packages.debian.org/jessie-backports/libgrpc-dev)
